#!/usr/bin/env python3
"""Refresh Vale's abbreviation exceptions from the RPC's public data."""

import argparse
import json
import re
import urllib.request
from pathlib import Path


SOURCE_REVISION = "2f79add2db8fd993dd163cda34a69490f36a152d"
SOURCE = f"https://raw.githubusercontent.com/rfc-editor-drafts/common/{SOURCE_REVISION}/abbreviations.json"
TERM = re.compile(r"^[A-Z][A-Z0-9]{1,}$")
BCP14 = ("MUST", "REQUIRED", "SHALL", "SHOULD", "RECOMMENDED", "MAY", "OPTIONAL")


def email_rule(terms: list[str], revision: str) -> str:
    """Build the email rule, excluding URLs and BCP 14 keywords."""
    known = sorted(set(terms) | set(BCP14))
    pattern = "|".join(re.escape(term) for term in known)
    return f"""extends: script
message: \"%s\"
link: https://www.rfc-editor.org/rfc/rfc7322.html#section-3.6
level: suggestion
scope: ~code
script: |
  text := import(\"text\")
  matches := []
  known := \"\\\\b(?:{pattern})\\\\b\"
  urls := text.re_find(\"https?://[^\\\\s<>]+\", scope, -1)
  candidates := text.re_find(\"\\\\b[A-Z][A-Z0-9]{{1,}}\\\\b\", scope, -1)
  if candidates != undefined {{
    for candidate in candidates {{
      m := candidate[0]
      ignored := false
      if urls != undefined {{
        for url in urls {{
          u := url[0]
          if m.begin >= u.begin && m.begin < u.begin + len(u.text) {{
            ignored = true
            break
          }}
        }}
      }}
      if !ignored && text.re_find(known, m.text, -1) != undefined {{
        ignored = true
      }}
      if !ignored {{
        expansion := text.re_find(\"(?i)\\\\b[A-Za-z][A-Za-z -]+[ ]+\\\\(\" + m.text + \"\\\\)\", scope, -1)
        if expansion != undefined && len(expansion) > 0 {{
          continue
        }}
        matches = append(matches, {{
          begin: m.begin,
          end: m.begin + len(m.text),
          message: \"Expand '\" + m.text + \"' on first use, unless it is a well-known abbreviation.\"
        }})
      }}
    }}
  }}

# Generated by scripts/update-abbreviations.py from:
# https://github.com/rfc-editor-drafts/common/blob/{revision}/abbreviations.json
# The email variant also skips URLs and BCP 14 keywords.
"""


def draft_rule(terms: list[str], level: str, revision: str) -> str:
    body = f"""extends: conditional
message: \"Expand '%s' on first use, unless it is a well-known abbreviation.\"
link: https://www.rfc-editor.org/rfc/rfc7322.html#section-3.6
level: {level}
scope: ~code
first: '\\b[A-Z][A-Z0-9]{{1,}}\\b'
second: '\\b[A-Za-z][A-Za-z -]+[ ]+\\(([A-Z][A-Z0-9]{{1,}})\\)'

# Generated by scripts/update-abbreviations.py from:
# https://github.com/rfc-editor-drafts/common/blob/{revision}/abbreviations.json
exceptions:
"""
    return body + "".join(f"  - {term}\n" for term in terms)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", type=Path, default=Path("IETF-Draft/Abbreviations.yml"))
    parser.add_argument("--source", default=SOURCE)
    parser.add_argument("--revision", default=SOURCE_REVISION)
    parser.add_argument("--level", default="warning", choices=("suggestion", "warning"))
    args = parser.parse_args()

    request = urllib.request.Request(args.source, headers={"User-Agent": "ietf-vale"})
    with urllib.request.urlopen(request) as response:
        records = json.load(response)

    terms = sorted({item["term"] for item in records if item.get("wellknown") and TERM.fullmatch(item["term"])})
    if args.level == "suggestion":
        body = email_rule(terms, args.revision)
    else:
        body = draft_rule(terms, args.level, args.revision)
    args.output.write_text(body, encoding="utf-8")
    print(f"wrote {len(terms)} exceptions to {args.output}")


if __name__ == "__main__":
    main()
