#!/usr/bin/env python3
"""Refresh Vale's abbreviation exceptions from the RPC's public data."""

import argparse
import json
import re
import urllib.request
from pathlib import Path


SOURCE_REVISION = "2f79add2db8fd993dd163cda34a69490f36a152d"
SOURCE = f"https://raw.githubusercontent.com/rfc-editor-drafts/common/{SOURCE_REVISION}/abbreviations.json"
TERM = re.compile(r"^[A-Z][A-Z0-9]{1,}$")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", type=Path, default=Path("IETF-Draft/Abbreviations.yml"))
    parser.add_argument("--source", default=SOURCE)
    parser.add_argument("--revision", default=SOURCE_REVISION)
    args = parser.parse_args()

    request = urllib.request.Request(args.source, headers={"User-Agent": "ietf-vale"})
    with urllib.request.urlopen(request) as response:
        records = json.load(response)

    terms = sorted({item["term"] for item in records if item.get("wellknown") and TERM.fullmatch(item["term"])})
    body = f"""extends: conditional
message: \"Expand '%s' on first use, unless it is a well-known abbreviation.\"
link: https://www.rfc-editor.org/rfc/rfc7322.html#section-3.6
level: warning
scope: ~code
first: '\\b[A-Z][A-Z0-9]{{1,}}\\b'
second: '\\b[A-Za-z][A-Za-z -]+[ ]+\\(([A-Z][A-Z0-9]{{1,}})\\)'

# Generated by scripts/update-abbreviations.py from:
# https://github.com/rfc-editor-drafts/common/blob/{args.revision}/abbreviations.json
exceptions:
"""
    body += "".join(f"  - {term}\n" for term in terms)
    args.output.write_text(body, encoding="utf-8")
    print(f"wrote {len(terms)} exceptions to {args.output}")


if __name__ == "__main__":
    main()
